# Generated by Django 6.0.3 on 2026-05-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='assignment_due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessons',
            name='assignment_instructions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='lessons',
            name='content_md',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='lessons',
            name='duration_min',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lessons',
            name='exercise',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessons',
            name='external_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='lessons',
            name='kind',
            field=models.CharField(choices=[('VIDEO', 'Video'), ('ARTICLE', 'Reading'), ('CHEATSHEET', 'Cheatsheet'), ('EXERCISE', 'Exercise'), ('QUIZ', 'Quiz'), ('ASSIGNMENT', 'Assignment'), ('RESOURCE', 'Resource'), ('DISCUSSION', 'Discussion')], default='VIDEO', max_length=16),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='additional_task',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='desc',
            field=models.TextField(blank=True, default=''),
        ),
    ]
