# Generated by Django 6.0.3 on 2026-03-18 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cover_img',
            field=models.ImageField(blank=True, null=True, upload_to='course/cover_img'),
        ),
    ]
