# Generated by Django 6.0.3 on 2026-03-21 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursestudent',
            name='certificate_pdf',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
    ]
