# Generated by Django 6.0.3 on 2026-05-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_lessons_assignment_due_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursestudent',
            name='completed_lectures',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
