# Generated by Django 6.0.3 on 2026-05-29 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_lessons_captions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseunit',
            options={'ordering': ['order', 'created_at']},
        ),
        migrations.AlterModelOptions(
            name='lessons',
            options={'ordering': ['order', 'created_at']},
        ),
        migrations.AddField(
            model_name='courseunit',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lessons',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
