# Generated by Django 6.0.3 on 2026-05-29 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_alter_courseunit_options_alter_lessons_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='assignmentsubmission',
            name='uniq_assignment_submission_per_lesson_student',
        ),
    ]
