# Generated by Django 6.0.3 on 2026-05-29 17:59

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_remove_assignmentsubmission_uniq_assignment_submission_per_lesson_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='allow_multiple_files',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AssignmentSubmissionFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('file', models.FileField(upload_to='assignments/submissions/')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='course.assignmentsubmission')),
            ],
            options={
                'db_table': 'assignment_submission_file',
                'ordering': ['created_at'],
            },
        ),
    ]
