# Generated by Django 6.0.3 on 2026-03-22 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_google_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_real_password',
            field=models.BooleanField(default=False),
        ),
    ]
