# Generated by Django 6.0.3 on 2026-05-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='show_timer',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='time_limit_min',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
