# Generated by Django 6.0.3 on 2026-03-21 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('PAID', 'paid'), ('CANCELED', 'canceled')], default='PAID', max_length=25),
        ),
    ]
